### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by MohWad** [mohawad-53/github-crash-course#1]
I think it looks better if the title is orange,

The styling rule could be changed like this:

```css
h1 {
  color: #e1920a;
}
```
